---
# Ansible collections. Install with:
#   ansible-galaxy collection install -r requirements.yml
collections:
  - name: cisco.ios
    version: ">=11.5.1"
  - name: ansible.netcommon
    version: ">=8.6.2"
  - name: ansible.utils
    version: ">=6.1.0"
